- type: entity
  parent: [ClothingUniformBase, ClothingUniformFoldableBase]
  id: ClothingUniformJumpsuitBartender
  name: 調酒師制服 | bartender's uniform
  description: 這身制服很整潔美觀。不過那條橫條就讓人有點遺憾了。 | A nice and tidy uniform. Shame about the bar though.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/bartender.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitJacketMonkey
  name: 調酒師的猴子夾克 | bartender's monkey jacket
  description: 一件像樣的外套，給一隻像樣的猴子。 | A decent jacket, for a decent monkey.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/punpun.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/punpun.rsi
  - type: SuitSensor
    controlsLocked: false
    randomMode: false
    mode: SensorCords

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitBartenderPurple
  name: 紫色的調酒師制服 | purple bartender's uniform
  description: 一套專門用來端飲料的紫色服裝。 | A special purple outfit to serve drinks.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/bartender_purple.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/bartender_purple.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitChaplain
  name: 軍牧的連身工作服 | chaplain's jumpsuit
  description: 這是一件黑色的連身衣，常被宗教人士穿著。 | It's a black jumpsuit, often worn by religious folk.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/chaplain.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/chaplain.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitChef
  name: 廚師制服 | chef uniform
  description: 沒有這個就做不了菜。 | Can't cook without this.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/chef.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/chef.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitClown
  name: 小丑服 | clown suit
  description: 嗶——！ | HONK!
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/clown.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/clown.rsi
  - type: Tag
    tags:
    - ClownSuit
    - WhitelistChameleon

- type: entity
  parent: ClothingUniformJumpsuitClown
  id: ClothingUniformJumpsuitClownBanana
  name: 香蕉小丑服 | banana clown suit
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/clown_banana.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/clown_banana.rsi
  - type: Construction
    graph: BananaClownJumpsuit
    node: jumpsuit
  - type: Armor
    modifiers:
      coefficients:
        Radiation: 0.8

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitJester
  name: 小丑服 | jester suit
  description: 這件俏皮的洋裝，非常適合用來款待你的主人，叔公。 | A jolly dress, well suited to entertain your master, nuncle.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/jester.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/jester.rsi

- type: entity
  parent: ClothingUniformJumpsuitJester
  id: ClothingUniformJumpsuitJesterAlt
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/jester2.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/jester2.rsi

- type: entity
  parent: [ClothingUniformBase, ClothingUniformFoldableBase]
  id: ClothingUniformJumpsuitHydroponics
  name: 水耕栽培連身工作服 | hydroponics jumpsuit
  description: 散發出一股濃烈的泥土味。希望這只是髒了，而不是被弄髒了。 | Has a strong earthy smell to it. Hopefully it's merely dirty as opposed to soiled.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/hydro.rsi

- type: entity
  parent: [ClothingUniformBase, ClothingUniformFoldableBase]
  id: ClothingUniformJumpsuitJanitor
  name: 清潔工連身工作服 | janitor jumpsuit
  description: 那件給拿著拖把的可憐蟲穿的連身工作服。 | The jumpsuit for the poor sop with a mop.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/janitor.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitMime
  name: MIME 套裝 | mime suit
  description: ... | ...
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/mime.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/mime.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLibrarian
  name: 圖書館員連身工作服 | librarian jumpsuit
  description: 一件舒適的綠色毛衣，非常適合一位圖書策展人。 | A cosy green jumper fit for a curator of books.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/librarian.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/librarian.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitCurator
  name: 得體的西裝 | sensible suit
  description: 這很明智。實在太明智了…… | It's sensible. Too sensible...
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/curator.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/curator.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitPsychologist
  name: 心理學家西裝 | psychologist suit
  description: 我不會弄丟東西。只是把東西放在某些地方，後來卻想不起來放在哪裡了。 | I don't lose things. I place things in locations which later elude me.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/psychologist.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/psychologist.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitTramDriver
  name: 電車司機連身工作服 | tram driver jumpsuit
  description: 熨燙得完美無瑕，專為準備周全的專業人士而設。 | Perfectly ironed, for well-prepared professionals.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/tramdriver.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/tramdriver.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitReporter
  name: 記者套裝 | reporter suit
  description: 一位優秀的記者，終其一生都會保持懷疑精神。 | A good reporter remains a skeptic all their life.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/reporter.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/reporter.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitSafari
  name: 薩法里套裝 | safari suit
  description: 非常適合進行叢林探險。 | Perfect for a jungle excursion.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/safari.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/safari.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitJournalist
  name: 記者套裝 | journalist suit
  description: 如果新聞報導是優質的，那麼它本質上就是具爭議性的。 | If journalism is good, it is controversial, by nature.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/journalist.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/journalist.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitMonasticRobeDark
  name: 深色的修道袍 | dark monastic robe
  description: 這是一件深色的長袍，通常由宗教人士穿著。 | It's a dark robe, often worn by religious folk.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/monastic_robe_dark.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/monastic_robe_dark.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitMonasticRobeLight
  name: 淺色僧袍 | light monastic robe
  description: 這是一件輕便的長袍，通常由宗教人士穿著。 | It's a light robe, often worn by religious folk.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/monastic_robe_light.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/monastic_robe_light.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitMusician
  name: 音樂家的晚禮服 | musician's tuxedo
  description: 一款專為音樂愛好者設計的華麗燕尾服。非常適合任何酒廊演出！ | A fancy tuxedo for the musically inclined.  Perfect for any lounge act!
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/musician.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/musician.rsi

- type: entity
  parent: ClothingUniformJumpsuitClown
  id: ClothingUniformJumpsuitCluwne
  name: 克盧恩套裝 | cluwne suit
  suffix: Unremoveable
  description: 這該死的小丑服。 | Cursed cluwne suit.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/cluwne.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/cluwne.rsi
  - type: Unremoveable

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLawyerRed
  name: 紅色律師西裝 | red lawyer suit
  description: 一種由律師和愛出風頭的人穿著的、花俏的紅色西裝。 | A flashy red suit worn by lawyers and show-offs.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerred.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerred.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLawyerBlue
  name: 藍色律師西裝 | blue lawyer suit
  description: 一種由律師和愛出風頭的人穿著的、花俏的藍色西裝。 | A flashy blue suit worn by lawyers and show-offs.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerblue.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerblue.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLawyerBlack
  name: 黑色律師西裝 | black lawyer suit
  description: 一種低調的黑色西裝，既是律師也是黑幫分子所穿著的。 | A subtle black suit worn by lawyers and gangsters.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerblack.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerblack.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLawyerPurple
  name: 紫色律師西裝 | purple lawyer suit
  description: 一款時尚的紫色單品，深受律師與演藝界人士青睞。 | A stylish purple piece worn by lawyers and show people.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerpurple.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyerpurple.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitLawyerGood
  name: 一套像樣的律師西裝 | good lawyer's suit
  description: 一套俗氣的西裝，簡直是為犯罪辯護律師量身打造的！ | A tacky suit perfect for a CRIMINAL lawyer!
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyergood.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/lawyergood.rsi

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformOveralls
  name: 連身工作服 | overalls
  description: 非常適合在戶外工作。 | Great for working outdoors.
  components:
  - type: Sprite
    sprite: Clothing/Uniforms/Jumpsuits/Service/overalls.rsi
  - type: Clothing
    sprite: Clothing/Uniforms/Jumpsuits/Service/overalls.rsi
